### ISSUE TITLE
Fix references to code.google.com in README.

### ISSUE THREAD

**Issue by TheCodeArtist** [TheCodeArtist/chocosticks#4]
Migrate all the secondary content (wikis, pre-built downloads, supporting-files) from code.google.com into github and update the links in README to the new content within github itself.

**Comment by ManishAradwad** [comment]
Is this issue still open?? I'd love to fix this

**Comment by TheCodeArtist** [comment]
Yes. It is open. Pull Requests are welcome! :smiley:
